### ISSUE TITLE
Fabric iOS app not showing up on dashboard

### ISSUE THREAD

**Issue by pushkardeshmukh1992** [hypery2k/nativescript-fabric#116]
## What did you do?
Updated AndroidManifest.xml and info.plist with Fabric API key.

## What did you expect to happen?
Expected to show the app in fabric dashboard for both iOS and android.

## What happened instead?
Android app is showing in the fabric dashboard but not iOS.

## Your Environment

**NativeScript version: 3.3.1
**Java version: 1.8.0_101
**NodeJS and NPM version: 8.2.1 & 4.6.1
**Platform(s) running: iOS & Android

P.S: I logged the fabric object and checked if its initialized. `initDone` returns true.

**Comment by hypery2k** [comment]
can you try `nativescript-fabric@next`?

**Comment by pushkardeshmukh1992** [comment]
Caught up with different ios build issue. Yes I will try re-installing with command you mentioned and then let you know!

**Comment by hypery2k** [comment]
@pushkardeshmukh1992 Any news?

**Comment by Willis0826** [comment]
+1 , I tried the latest version `"nativescript-fabric": "^1.0.6-bugfix-android-29"`, and **I couldn't get through the _verify installation page_ in IOS(10.2.1)**. 
<img src="https://i.imgur.com/SyyRigS.png" height="300">
I followed the instruction to set up project, and I log out the Fabric object after using `Fabric.init()`, it shows `{"initDone":true}`. Everything seems work perfectly, not sure if it is a bug or not.

**Comment by hypery2k** [comment]
really strange

**Comment by pushkardeshmukh1992** [comment]
@hypery2k Hey any update on this?
I tried installing with `nativescript-fabric@next` and now app crashes with following exception. (iOS)

> ***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
2018-01-15 14:09:50.219844+0530 globalproducthybridapp[3521:1592611] 1   0x10118ae2c -[TNSRuntime executeModule:referredBy:]
1   0x10118ae2c -[TNSRuntime executeModule:referredBy:]
2018-01-15 14:09:50.220815+0530 globalproducthybridapp[3521:1592611] 2   0x1000f44f8 main
2   0x1000f44f8 main
2018-01-15 14:09:50.220844+0530 globalproducthybridapp[3521:1592611] 3   0x18497959c <redacted>
3   0x18497959c <redacted>
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-fabric/fabric.js:5:39
JavaScript error:
2018-01-15 14:09:50.221037+0530 globalproducthybridapp[3521:1592611] file:///app/tns_modules/nativescript-fabric/fabric.js:5:39: JS ERROR Error: Could not find module './fabric.ios.appdelegate'. Computed path '/var/containers/Bundle/Application/8E613AEB-D26A-41CD-9485-F87D577ED26B/globalproducthybridapp.app/app/tns_modules/nativescript-fabric/fabric.ios.appdelegate'.

> file:///app/tns_modules/nativescript-fabric/fabric.js:5:39:

> JS ERROR Error: Could not find module './fabric.ios.appdelegate'. Computed path '/var/containers/Bundle/Application/8E613AEB-D26A-41CD-9485-F87D577ED26B/globalproducthybridapp.app/app/tns_modules/nativescript-fabric/fabric.ios.appdelegate'.
Message from debugger: failed to send the k packet

**Comment by hypery2k** [comment]
not yet. currently working on a bugfix for the crash issue. Hope to fix this [here](https://github.com/hypery2k/nativescript-fabric/tree/bugfix/114_app_crash.)

But thanks for the log entry. Will help me
