### ISSUE TITLE
io is undefined

### ISSUE THREAD

**Issue by Sharique-Hasan** [hypery2k/nativescript-fabric#117]
Since you have not included io.fabric sdk in your include.gradle. Project doesn't get build and gives out error of io is undefined.

**Comment by hypery2k** [comment]
which version of the plugin you're using?

**Comment by Sharique-Hasan** [comment]
Latest version

**Comment by hypery2k** [comment]
version 1.0.6?

**Comment by Sharique-Hasan** [comment]
Yes. Include.gradle doesn't include the fabric sdk

**Comment by hypery2k** [comment]
this issue should be resolved when #114 is fixed
