### ISSUE TITLE
Configuration Issue error during iOS build

### ISSUE THREAD

**Issue by terreb** [hypery2k/nativescript-fabric#119]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/hypery2k/nativescript-fabric/master/CONTRIBUTING.md).

## What did you do?

Followed the instruction in readme. Then build the project for iOS.

## What did you expect to happen?

I sure excepted the build succeeded. 

## What happened instead?

Instead I get this error:

2018-01-17 10:38:01.837 uploadDSYM[3030:57137] Fabric.framework/run 1.6.2 (205)
error: Fabric: Configuration Issue

Fabric API key not valid. Your Fabric run script build phase should contain your API key:
./Fabric.framework/run INSERT_YOUR_API_KEY INSERT_YOUR_BUILD_SECRET

I did registered on Fabric, created fabric.json in the root of the project and copy paste API key and secret there.
 

## Your Environment

**NativeScript version:**
3.4.1
**Java version:**
irrelevant since I get the error for iOS
**NodeJS and NPM version:**
NodeJS 8.9.1
NPM 5.6.0
**Platform(s) running:**
iOS 9.3
Xcode 9.2
Mac os 10.13.2

## Demo Project

I better avoid exposing my API keys:) I hope the info above is enough for you to give me any insight on where the problem could be.

**Comment by styrken** [comment]
Seems like the build phase `Configure Fabric` does not input the correct keys. Also, now i have the build step two times - does it check if it already exists?

`<prev path>/platforms/ios/Pods/Fabric/run undefined undefined`

**Comment by hypery2k** [comment]
which plugin version you’re using?

**Comment by hypery2k** [comment]
closed due to no response after a week

**Comment by Jaroslav84** [comment]
Fabric.framework/run 1.7.0 (208)

**Comment by hmrocket** [comment]
If you are using Crashlytics remove the Fabric keys form the info.plist the script works, without the need of any keys/params. The Fabric initialization build script is trying to read.
