### ISSUE TITLE
Installation doubt's

### ISSUE THREAD

**Issue by abolinhas** [hypery2k/nativescript-fabric#121]
Hi,
I'm trying add nativescript-fabric to my project, my question is:
1º How can I get fabric api's? On fabric dashborad before getting api's it says that first I need to install the plugin on SDK.
2º There is a manual way https://fabric.io/kits/android/crashlytics/install, but wish gradle file I need to edit?
Best regards

**Comment by hypery2k** [comment]
see https://github.com/hypery2k/nativescript-fabric#installation for more details. Will be updated for the upcoming version release. 

The current release has issue with NativeScript 3!!
