### ISSUE TITLE
Fabric no longer provides a API key/secret pair.

### ISSUE THREAD

**Issue by r0zar** [hypery2k/nativescript-fabric#122]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/hypery2k/nativescript-fabric/master/CONTRIBUTING.md).

## What did you do?

Followed the setup steps

## What did you expect to happen?

Find a API key and secret on Fabrics site

## What happened instead?

They no longer supply a API key/secret, only a single API key.

**Comment by frapaa** [comment]
I can still see both API key and secret on https://fabric.io/kits/ios/crashlytics/install

**Comment by hypery2k** [comment]
is
