### ISSUE TITLE
How to  login into Crashlytics.I used this code.I didn't receive any apk file uploaded in to my Fabric account.

### ISSUE THREAD

**Issue by priyangamani** [hypery2k/nativescript-fabric#128]
var nativescript_fabric_1 = require("nativescript-fabric");
nativescript_fabric_1.Fabric.init();
nativescript_fabric_1.Fabric.logSignUp("xyz@gmail.com",true);
nativescript_fabric_1.Fabric.logLogin("xyz@gmail.com", true);
nativescript_fabric_1.Fabric.logContentView();
nativescript_fabric_1.Fabric.logCustomEvent("","");
nativescript_fabric_1.Fabric.logError("error","messsge");

Environment
tns version : 3.4.3
node version : v6.11.0
npm version : 5.8.0
tns-core-modules: "^3.3.0"
nativescript-fabric: "^1.0.6-develop-133"

Where i need to give my username and password..Iam using javascript.I tried this method it won't work.Plz give some suggestion on this one.Please refer the screenshots for futher info...

![image](https://user-images.githubusercontent.com/6038069/39752147-227841fe-52ed-11e8-810e-f992c0ace8e3.png)

**Comment by etabakov** [comment]
In order to use the services of Fabric (like Crashlytics, Analytics, etc.) you need to first create an account on [their website](https://fabric.io/home). After signing up, you will receive an API key and Secret key - put these key on the respective place in the nativescript-fabric plugin configuration. After that you should be able to see activity in you application dashboard in fabric.io.

**Comment by priyangamani** [comment]
@etabakov 
Fabric Crashlytics “Hmmm, seems like your kit isn't activating” whilst verifying install.(ios)
However i am current getting the "Hmmm, seems like your kit isn't activating" message on the Fabric Controller after following the instruction to run the app in Xcode. I have looked around but the solutions i have found haven't made any difference.
![screen shot 2018-05-10 at 8 55 12 pm](https://user-images.githubusercontent.com/6038069/39870852-641c16d6-5495-11e8-9fdb-bb7ce003047e.png)

**Comment by hypery2k** [comment]
did you have a fabric.json in your project?

**Comment by priyangamani** [comment]
yes having inside the project .
![image](https://user-images.githubusercontent.com/6038069/40036768-ebbbf36e-583b-11e8-9a43-a296fb63c417.png)

**Comment by hypery2k** [comment]
and the values are not empty?
```
{
    "using_ios": "y",
    "using_android": "y",
    "api_key": "<not_empt>",
    "api_secret": "<not_empt>"
}
```

**Comment by priyangamani** [comment]
![image](https://user-images.githubusercontent.com/6038069/40037057-b3ab3bfe-583d-11e8-98d7-8363542fb437.png)

**Comment by hypery2k** [comment]
did you try to use version 2.0.2?

**Comment by priyangamani** [comment]
Version 2.0.2.Still problem will exist in ios
![image](https://user-images.githubusercontent.com/6038069/40162536-dd470b00-59e6-11e8-87c0-afe316625205.png)

**Comment by hypery2k** [comment]
you have to run `pod repo update`

**Comment by hypery2k** [comment]
but these are different errors you are describing and the above one does not relate to Fabric
