### ISSUE TITLE
App crashes on launch in  android

### ISSUE THREAD

**Issue by ManiPriya11** [hypery2k/nativescript-fabric#131]
@hypery2k 

  By using nativescript-fabric plugin the app starts with error.

Package.json
  "nativescript": {
    "id": "org.nativescript.testing",
    "tns-android": {
      "version": "3.4.2"
    }
  },
"tns-core-modules": "^3.4.1"
 "nativescript-fabric": "^2.0.2",

//Error Log 
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.testing on device 192.168.56.101:5555.
ActivityManager: Start proc 5327:org.nativescript.testing/u0a82 for activity org.nativescript.testing/com.tns.NativeScriptActivity
ActivityManager: Process org.nativescript.testing (pid 5327) has died

**Comment by hypery2k** [comment]
the plugin works only for NativeScript 4+ beginning with version 2, see [here](https://github.com/hypery2k/nativescript-fabric/releases/tag/v2.0.0)
