### ISSUE TITLE
FabricErrorHandler makes Angular app super crashable

### ISSUE THREAD

**Issue by hosikiti** [hypery2k/nativescript-fabric#134]
If I use `FabricModule.forRoot()` , angular app crashes super easily.
For example, following TypeScript codes will cause JavaScript error.

```
let x: any = {};
let msg = x.y.getMessage(); // This line causes -> TypeError: undefined is not an object (evaluating 'x.y.getMessage')
```

Without using `FabricModule.forRoot()`, the line shows JavaScript errors on console but apps do NOT crash. However if you use `FabricModule.forRoot()`, the line causes instant app freeze and crash. 

It seems following line of `errorhandler.ts` causes app crash:

https://github.com/hypery2k/nativescript-fabric/blob/d35bf9104e69cde495116ad948aafb0ab2149635/src/app/errorhandler.ts#L60

If I commented out ` throw err; `, apps stop crashing.

In development, this crash behavior is acceptable. But in production, app crash can seriously hurt your app's credibility.  So do you think you could replace `throw err;` with simple console output something like following:

```
console.error(err, err.stack);
```

**Comment by hypery2k** [comment]
this behaviour is intentional: An Angular Error Handler should catch errors, handle it with his own logic and rethrow it. Why should you use an ErrorHandler if you don't want to handle it?

**Comment by hypery2k** [comment]
this beviauoru

**Comment by hosikiti** [comment]
@hypery2k If this behaviour is intentional as you said, I think it should be documented somewhere. Although I wanted to handle error, I didn't expect adding this ErrorHandler would cause unexpected crash in production.

**Comment by hypery2k** [comment]
got it, would like to make it configurable, but not having time for this. I removed the rethrow. If the CI build went through, you can give the @next version a try.
