### ISSUE TITLE
Support for Answers and other Fabric methods

### ISSUE THREAD

**Issue by cmckni3** [hypery2k/nativescript-fabric#135]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/hypery2k/nativescript-fabric/master/CONTRIBUTING.md).

Add more methods for `Answers` such as level start, level end, purchase, etc.

![image](https://user-images.githubusercontent.com/735717/49100387-6cf73c80-f239-11e8-8a33-6742cd83004d.png)

## Your Environment

**NativeScript version:** 4.2.2
**Plugin version:** 2.0.2
**Java version:**
**NodeJS and NPM version:** 10.13.0
**Platform(s) running:** iOS

**Comment by hypery2k** [comment]
any PR is welcome
