### ISSUE TITLE
Android: How to request API key and API secret?

### ISSUE THREAD

**Issue by svzi** [hypery2k/nativescript-fabric#24]
Hi there!

I really appreciate your work on this plugin. 👍 

I've tried to incorporate this functionality into our app, because we planed on using fabric.io for months. So I was really excited to see the steady progress on this repo. :-)

But I learned it's already hard to gather the required API key and API secret to run the plugin with. Do you have any idea on how to request it? The official fabric.io documentation doesn't help as much here, as they require the official Android Studio to request the key, as far as I understood.

Any help would be really much appreciated!

Best,
Sven

**Comment by svzi** [comment]
I also wonder if we need to modify the build.gradle file, as described in the link you provided: https://fabric.io/kits/android/crashlytics/install

**Comment by hypery2k** [comment]
Go the [Crashlytics](https://fabric.io/kits/ios/crashlytics/install) and pick of the needed API-Key and API-Secret:

![](https://github.com/hypery2k/nativescript-fabric/blob/develop/etc/crashlytics_configuration.png?raw=true)

Create a file fabric.json in the project root folder and add the API-Key and API-Secret: 

```
{
    "apiKey": "",
    "apiSecret": ""
}
```

**Comment by hypery2k** [comment]
hope that helps

**Comment by svzi** [comment]
Thanks for your quick help! 👍 

Now I was finally able to gather the required information. I've updated my fabric.json and checked that the keys have been populated to the fabric.properties from the hook script as well. All fine, thanks for that part so far.

Sadly it still doesn't work. It crashes as soon as I try to log something. Do I need to wait until the application is fully loaded? I've tried with this code in my app.ts and it crashes the app right on start up:

`import {Fabric} from 'nativescript-fabric';

Fabric.init();
Fabric.logError({error: true, cause: 'just a test error'}, 'test log message');
`

This is the stacktrace from the device:

`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
    io.fabric.sdk.android.Fabric.singleton(Fabric.java:273)
    io.fabric.sdk.android.Fabric.getKit(Fabric.java:524)
    com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:188)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.access$1600(ActivityThread.java:150)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
File: "file:///data/data/com.svzi.test.beta/files/app/tns_modules/nativescript-fabric/fabric.js, line: 56, column: 48

StackTrace: 
	Frame: function:'CrashlyticsAndroidPlugin.logError', file:'file:///data/data/com.svzi.test.beta/files/app/tns_modules/nativescript-fabric/fabric.js', line: 56, column: 49
	Frame: function:'', file:'file:///data/data/com.svzi.test.beta/files/app/app.js', line: 5, column: 30
	Frame: function:'require', file:'', line: 1, column: 266


Error: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
    io.fabric.sdk.android.Fabric.singleton(Fabric.java:273)
    io.fabric.sdk.android.Fabric.getKit(Fabric.java:524)
    com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:188)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.access$1600(ActivityThread.java:150)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'CrashlyticsAndroidPlugin.logError', file:'file:///data/data/com.svzi.test.beta/files/app/tns_modules/nativescript-fabric/fabric.js', line: 56, column: 49
	Frame: function:'', file:'file:///data/data/com.svzi.test.beta/files/app/app.js', line: 5, column: 30
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
	at android.app.ActivityThread.access$1600(ActivityThread.java:150)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
    io.fabric.sdk.android.Fabric.singleton(Fabric.java:273)
    io.fabric.sdk.android.Fabric.getKit(Fabric.java:524)
    com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:188)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.access$1600(ActivityThread.java:150)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
File: "file:///data/data/com.svzi.test.beta/files/app/tns_modules/nativescript-fabric/fabric.js, line: 56, column: 48

StackTrace: 
	Frame: function:'CrashlyticsAndroidPlugin.logError', file:'file:///data/data/com.svzi.test.beta/files/app/tns_modules/nativescript-fabric/fabric.js', line: 56, column: 49
	Frame: function:'', file:'file:///data/data/com.svzi.test.beta/files/app/app.js', line: 5, column: 30
	Frame: function:'require', file:'', line: 1, column: 266


Error: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
    io.fabric.sdk.android.Fabric.singleton(Fabric.java:273)
    io.fabric.sdk.android.Fabric.getKit(Fabric.java:524)
    com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:188)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:580)
    com.tns.Runtime.run(Runtime.java:574)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.access$1600(ActivityThread.java:150)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'CrashlyticsAndroidPlugin.logError', file:'file:///data/data/com.svzi.test.beta/files/app/tns_modules/nativescript-fabric/fabric.js', line: 56, column: 49
	Frame: function:'', file:'file:///data/data/com.svzi.test.beta/files/app/app.js', line: 5, column: 30
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:580)
	at com.tns.Runtime.run(Runtime.java:574)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
	... 8 more`

**Comment by hypery2k** [comment]
can you tell me more about your setup?

which nativescript version you're using? Are using angular?

**Comment by svzi** [comment]
Sure, I'm using NativeScript 2.5.0. I'm using TypeScript, but no(!) Angular.

What else do you want to know? 🤔

**Comment by hypery2k** [comment]
could be an issue during the bootstrap. Have to investigate this. CurrentlyI just tested it via nativescript-angular. Have to create a sample project for verification

**Comment by svzi** [comment]
Btw do I need to wait until the application is fully loaded? Or at least is there anything that needs to be initialized before as well?

**Comment by hypery2k** [comment]
normally you don't have to wait. in angular i do it before bootstrap

**Comment by svzi** [comment]
I've stepped through my application and your plugin a little bit and I found out something you should probably mention in the README.

Your initialization depends on the `application.activityStarted` Event on Android. This event will be thrown soon after you call `application.start(...);`. So a proper way, in my opinion and from what I saw in my debug logs, to start using this plugin would be somewhen after the `application.resumeEvent`.

Calling `Fabric.logError({error: true, cause: 'just a test error'}, 'test log message');` doesn't throw an error anymore. Sadly my Dashboard (https://fabric.io/dashboard) seems to be empty or not initialized, I get re-directed to https://fabric.io/onboard. :(

How long does it take until the data is available in the dashboard?

**Comment by svzi** [comment]
How do we need to register the app with fabric.io? As far as I know does the Android Studio plugin from Crashlytics some kind of registration step to setup the app initially. And when you setup the app for iOS, it tries to connect to the app as well.

For that reason I assume you're using APP keys that were used (and connected) before. Could that be the case?

**Comment by svzi** [comment]
I was finally able to get it up and running, at least with a fresh sample app. I will try to add the plugin to our main app soon and I hope I will get it running this time.

Thanks for your help so far! 👍
