### ISSUE TITLE
FR: Add SignUp Event

### ISSUE THREAD

**Issue by svzi** [hypery2k/nativescript-fabric#25]
I would like to use the SignUp Event for our app. I've already made the needed coding. Will send a PR soon. 

I've also updated the initialization of the plugin for Android. I needed to enable the `debuggable`flag of the Fabric instance, in order to get it connected to my app in the fabric.io dashboard.

**Comment by hypery2k** [comment]
thanks. Currently busy with other stuff. If sending a PR please push it to the develop branch

**Comment by svzi** [comment]
Read that too late, sorry. Can I somehow change my PR afterwards?

**Comment by svzi** [comment]
Changed it to develop branch.

**Comment by hypery2k** [comment]
no problem will merge the PR tomorrow manually ;)

Thanks for your contribution

**Comment by svzi** [comment]
You're welcome, thanks for the plugin. 👍

**Comment by hypery2k** [comment]
you can try if the nightly build is working for you:
```
tns plugin add nativescript-fabric@next
```

Will try to release within this week

**Comment by hypery2k** [comment]
new version is available

**Comment by svzi** [comment]
Great, thanks a lot! 👍
