### ISSUE TITLE
fabric.properties error

### ISSUE THREAD

**Issue by regar007** [hypery2k/nativescript-fabric#4]
can someone tell me how to proceed after adding the plugin. 

I m getting error "Missing fabric.properties, check the fabric.properties.sample file." from include.gradle
I tried adding a fabric.properties file with apiSecret="e8..." content. and no error but I dont see my app in fabric.io

please tell me what I am missing here.

I feel this [this](https://www.nativescript.org/blog/migrating-n-android-plugins-from-version-1.7-to-2.0) is relative but don't understand. someone please guide me.

**Comment by hypery2k** [comment]
The plugin is not finished as mentioned in the README
It's only a rough skeleton which currently only have basic functionality on android

**Comment by regar007** [comment]
thanks for getting back to my silly issue man.

Appreciate the work :+1:

**Comment by hypery2k** [comment]
you need to init the plugin also within your app (currently **only for Android**):
```
import {Crashlytics} from 'nativescript-fabric';

declare var io: any, com: any;

try {
  Crashlytics.init();
...
} catch (e) {
  Crashlytics.log(e);
  throw e;
}

```

**Comment by regar007** [comment]
Cool! :+1: above make sense,  I will try it.
