### ISSUE TITLE
Stuck on "Follow the instructions on this page to install Crashlytics for Android to your first project!"

### ISSUE THREAD

**Issue by smarza** [hypery2k/nativescript-fabric#50]
@hypery2k @svzi
Hello guys!

I'm running a Nativescript/Angular project with nativescript-fabric implemented, but even after followed all the instructions here, and building without any ERROR messages, the fabric.io dashboard seems to be stucked showing the installation message:

> Welcome to Fabric  —  Follow the instructions on this page to install Crashlytics for Android to your first project!

TNS: 2.5.3
NodeJs: 7.7.1

Does anyone have any clue about what is happining?

Please let me know if you need any code of my project to discuss this issue.
Thanks!

> "dependencies": {
>     "@angular/common": "~2.4.10",
>     "@angular/compiler": "~2.4.10",
>     "@angular/core": "~2.4.10",
>     "@angular/forms": "~2.4.10",
>     "@angular/http": "~2.4.10",
>     "@angular/platform-browser": "~2.4.10",
>     "@angular/platform-browser-dynamic": "~2.4.10",
>     "@angular/router": "~3.4.10",
>     "angular2-uuid": "^1.1.1",
>     "nativescript-angular": "1.4.1",
>     "nativescript-audio": "^3.0.1",
>     "nativescript-cardview": "^1.3.2",
>     "nativescript-fabric": "^0.3.0",
>     "nativescript-fancyalert": "^1.1.2",
>     "nativescript-fresco": "^1.0.16",
>     "nativescript-geolocation": "0.0.19",
>     "nativescript-intl": "~0.0.10",
>     "nativescript-loading-indicator": "^2.2.2",
>     "nativescript-local-notifications": "^1.2.1",
>     "nativescript-localstorage": "^1.1.0",
>     "nativescript-ng2-slides": "0.0.9",
>     "nativescript-plugin-firebase": "3.10.0",
>     "nativescript-pulltorefresh": "^1.1.10",
>     "nativescript-ripple": "^1.1.0",
>     "nativescript-social-share": "^1.3.2",
>     "nativescript-telerik-ui": "1.6.2",
>     "nativescript-theme-core": "^1.0.3",
>     "nativescript-toast": "^1.4.5",
>     "ngx-pipes": "^1.4.6",
>     "reflect-metadata": "~0.1.10",
>     "rxjs": "5.0.3",
>     "tns-core-modules": "2.5.2",
>     "tns-platform-declarations": "^2.5.2"
>   },
>   "devDependencies": {
>     "@angular/compiler-cli": "~2.4.10",
>     "@ngtools/webpack": "1.2.13",
>     "babel-traverse": "6.23.1",
>     "babel-types": "6.23.0",
>     "babylon": "6.16.1",
>     "codelyzer": "^2.0.1",
>     "copy-webpack-plugin": "~4.0.1",
>     "css-loader": "~0.26.4",
>     "extract-text-webpack-plugin": "~2.1.0",
>     "fs-extra": "~2.0.0",
>     "glob": "^7.1.1",
>     "lazy": "1.0.11",
>     "markdown-snippet-injector": "^0.2.2",
>     "nativescript-dev-android-snapshot": "~0.0.7",
>     "nativescript-dev-typescript": "^0.3.7",
>     "nativescript-dev-webpack": "^0.3.6",
>     "opener": "^1.4.3",
>     "raw-loader": "~0.5.1",
>     "resolve-url-loader": "~2.0.2",
>     "rimraf": "^2.6.1",
>     "tar.gz": "^1.0.5",
>     "tns-platform-declarations": "^2.5.2",
>     "tslint": "~4.5.1",
>     "typescript": "2.1.6",
>     "webpack": "2.2.1",
>     "webpack-sources": "~0.2.0",
>     "zone.js": "0.7.2",
>     "nativescript-css-loader": "~0.26.1"
>   },

**Comment by svzi** [comment]
Hi @smarza,

I've also had some trouble integrating this plugin the first time into my existing project (just plain TypeScript, no Angular2). I was stuck at the welcome screen of the dashboard as well. After some tries I set up a little test project, which did nothing except integrating this plugin.

As far as I remembered that sample app registered with fabric.io, for whatever reason. I need to admit that I didn't spend much time on finding the differences, but with the help of the registered sample app I was able to register my real project as well. I know this is not a step-by-step solution for you, but maybe it can point you in the right direction.

Good luck with it!

Best,
Sven

**Comment by smarza** [comment]
Hi @svzi,

Indeed your case was very helpful to me.

In order to test, I temporarily removed nativescript from the equation, so I set up an empty project on Android Studio with fabric plugin installed, and the fabric.io dashboard worked. After that, I ran my nativescript app without change a code... and magically worked.

**So far, I think that should be a good advice to everyone: set up an empty project in order to initializate the fabric.io dashboard.**

Thanks for you help.
I'm closing this issue for now, please feel free to open the discusssion again if you want. okay?

Regards,
Ricardo.
