### ISSUE TITLE
Not initializing on Android

### ISSUE THREAD

**Issue by agisboye** [hypery2k/nativescript-fabric#52]
I'm getting the following output when calling `Fabric.init()` on Android (device & simulator):

E/Fabric  (13008): 	at com.tns.Runtime.callJSMethodNative(Native Method)
E/Fabric  (13008): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethodNative(Native Method)
E/Fabric  (13008): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
E/Fabric  (13008): 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)

No network requests are being made to Fabric. I've added the `fabric.json` file and included the Fabric API key in `AndroidManifest.xml`. There are no issues on iOS.

**Comment by hypery2k** [comment]
which version of the plugin you're using?

**Comment by hypery2k** [comment]
closed due to no response
