### ISSUE TITLE
Error: Failed to find module @angular/core

### ISSUE THREAD

**Issue by leoelcoder** [hypery2k/nativescript-fabric#66]
This plugin only works with angular?
I'm currently working on an app using vanilla, and when try to
`Fabric.init()` the app crash 

```
var Fabric = require('nativescript-fabric');
Fabric.init();
```
after app launch have this

Error: Failed to find module `@angular/core`

I've created a new project and following your instructions and get same result also

**Comment by hypery2k** [comment]
I currently don't have time to work on this, but any PR is welcome

**Comment by hypery2k** [comment]
you give `nativescript-fabric@1.0.0-87-develop` a try. Need to add end2end tests for future verification

**Comment by leoelcoder** [comment]
Using `nativescript-fabric@1.0.0-87-develop` is no more `Error: Failed to find module @angular/core` 
Doing this:

```
var Fabric = require('nativescript-fabric');
Fabric.init();
````

Now get this 

Error: Fabric.init is not a function.

**Comment by hypery2k** [comment]
can you please post the following output (before Fabric.init)?
console.log(Fabric);
console.log(JSON.stringify(Fabric))

**Comment by leoelcoder** [comment]
In my app.js

```require("./bundle-config");
var application = require("application");
var Fabric = require('nativescript-fabric');
console.log(Fabric);
console.log(JSON.stringify(Fabric));
console.dir(Fabric);
Fabric.init();
application.start({ moduleName: "main-page" });
```

log output
```
JS: [object Object]
JS: {"Fabric":{"initDone":false}}
JS: === dump(): dumping members ===
JS: {
JS:     "Fabric": {
JS:         "initDone": false
JS:     }
JS: }
JS: === dump(): dumping function and properties names ===
JS: === dump(): finished ===
```
Error: Fabric.init is not a function.

**Comment by juliosueiras** [comment]
@leoelcoder have you try 
```ts
import {Fabric} from 'nativescript-fabric'
Fabric.init()
```
or 
```ts
var fabric = require('nativescript-fabric')
fabric.Fabric.init()
```

**Comment by hypery2k** [comment]
@juliosueiras is right. as you're not using ES6 import. you have to use his suggestions
