### ISSUE TITLE
ios Issue when building

### ISSUE THREAD

**Issue by johnnyzen** [hypery2k/nativescript-fabric#80]
Hi there

Gerring this error when building ios:

` !] Unable to satisfy the following requirements:

- `Crashlytics (~> 3.8.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Crashlytics (~> 3.8.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
Processing node_modules failed. Error: Command pod failed with exit code 1 `

**Comment by hypery2k** [comment]
can't you run `pod repo update` manually?

**Comment by hypery2k** [comment]
closed due to no further response
