### ISSUE TITLE
Android app not being added to fabric

### ISSUE THREAD

**Issue by johnnyzen** [hypery2k/nativescript-fabric#81]
Hi there.

I have added everything as per guide, but nothing is appearing in Fabric.

I am assuming it should get added automatically?

Best

**Comment by hypery2k** [comment]
yes should be added to fabric. Do you get any errors?

**Comment by johnnyzen** [comment]
no errors

**Comment by hypery2k** [comment]
did you just build the app or also run it after building on the device?

**Comment by sittingbool** [comment]
Having the same issue. I ran it in emulator, build a release, nothing worked. It also seems to be missing in the build.gradle

**Comment by hypery2k** [comment]
once again, did you tried to run the app? Building is not enough

**Comment by sittingbool** [comment]
As I said: build, run, do a release build. Fabric.init() is called, no errors. If I remove the fabric.json I get an error saying that I should add one, so its there...

**Comment by sittingbool** [comment]
I thought it could be the same problem as in here: https://github.com/corymsmith/react-native-fabric/issues/119 but I#m not that good with configuring the gradle files.

**Comment by alexdohmen** [comment]
should be solved with https://github.com/hypery2k/nativescript-fabric/pull/88

**Comment by Ablankzin** [comment]
I tested with develop branch and have same problem. I'm using TNS 3.

**Comment by Ablankzin** [comment]
You can update npm with this fix?

**Comment by hypery2k** [comment]
I've published version 1.0.6
