### ISSUE TITLE
multiple run scripts and linker error iOS

### ISSUE THREAD

**Issue by sittingbool** [hypery2k/nativescript-fabric#85]
Thank you for that great plugin. I just have one very annoying issue building iOS. I started with the 0.5 Version, now updated to 1.0.5 but the issue was with me all the time: each time i run the app with your plugin installed it creates the run-script in ios build phases again. Thats not a problem as long as you dont want to archive. When I archive i get a linker error until I delete all those run scripts or do a platform remove ios platform add ios. How can I solve this?

**Comment by hypery2k** [comment]
can you post more details about your setup (tns version, node version, os) and any log output?

**Comment by sittingbool** [comment]
tns is 3.1.1, node is 6.11.0, OS is Mac OSX sierra 10.12.5

**Comment by sittingbool** [comment]
Any progress. Btw. I'm having this on all of my apps and two different machines.
<img width="716" alt="bildschirmfoto 2017-08-16 um 06 50 28" src="https://user-images.githubusercontent.com/12949701/29347899-0c58ca38-8250-11e7-8a71-bbfb7cc83a3b.png">

**Comment by sittingbool** [comment]
Just ran into an output:

```/bin/sh -c /Users/.../Library/Developer/Xcode/DerivedData/halitosis-cwvhtfmnjozhvaadiwxloeadgggr/Build/Intermediates/halitosis.build/Debug-iphonesimulator/halitosis.build/Script-AFFD493795874219AE3EBD8C.sh
/Users/.../Projects/halitosis-app/halitosis/platforms/ios/Pods/Fabric/run: fork: Resource temporarily unavailable
/Users/.../Projects/halitosis-app/halitosis/platforms/ios/Pods/Fabric/run: line 18: /Users/.../Projects/halitosis-app/halitosis/platforms/ios/uploadDSYM: No such file or directory

* BUILD FAILED *


The following build commands failed:
	PhaseScriptExecution Configure\ Fabric /Users/.../Library/Developer/Xcode/DerivedData/halitosis-cwvhtfmnjozhvaadiwxloeadgggr/Build/Intermediates/halitosis.build/Debug-iphonesimulator/halitosis.build/Script-AFFD493795874219AE3EBD8C.sh
(1 failure)
Multiple errors were thrown:
Command xcodebuild failed with exit code 65
# run ios```

had to delete platforms folder and rerun

**Comment by sittingbool** [comment]
Any update on this? I have constant and major problems because of this bug? I did some debugging. The problem is that every time the system merges the info.plist this run script will be added. I'm not shure how to check that it already exists but that would be the solution.
Just now I had to kill my browser because this bug opened the fabric.io page about 200 times and my whole system got fried. Every time I make an archive it gives me errors and so on... PLEASE can you do something about this? It's driving me crazy. I'll help as much as I can.

**Comment by hypery2k** [comment]
I think I'm able to [reproduce](https://martinreinhardt-online.de/jenkins/blue/organizations/jenkins/NPM%2Fnativescript-fabric/detail/ci_build/16/pipeline) the issue. Hoping to find time for this.

**Comment by hypery2k** [comment]
could you try with `nativescript-fabric@1.0.6-ci-build-19`?

**Comment by TheOnlyMatt** [comment]
I have the same problem, app is building successfully with android, but fails with exit code 65 on iOS  :(

**Comment by hypery2k** [comment]
fixed in develop
