### ISSUE TITLE
App not appearing on Fabric (NS 2.5.0)

### ISSUE THREAD

**Issue by pedromareis** [hypery2k/nativescript-fabric#89]
Hey,

I'm trying to use Crashlytics on my NativeScript app and I've followed all the steps of the Installation but it won't work. Is it possible to use the plugin with NativeScript 2.5.0 since I don't want to upgrade my app for now...?

More info:
- I'm developing my app for Android using VS Code + NS 2.5.0 + Cli;
- Plugin version: "nativescript-fabric": "^0.3.1";
- I have the fabric.json file, the meta-data line on AndroidManifest.xml and the output for _console.log(JSON.stringify(crashlytics.Fabric));_ is {"initDone":true};
- I've also tried to remove node_modules + platforms + hooks folder, build (debug and release versions) and run my app.

Can anyone help me?
Thanks in advance

**Comment by Ablankzin** [comment]
You tried to use last version of plugin?

**Comment by pedromareis** [comment]
Yes, it says it isn't supported by NativeScript 2.5.0.

**Comment by hypery2k** [comment]
which version did you tried?

**Comment by pedromareis** [comment]
@hypery2k I've tried the versions 0.3.1 and 1.0.6 of the plugin on my NS 2.5.0 project...

**Comment by pedromareis** [comment]
Also, I don't know if this helps but I get this errors related to the plugin on the command prompt when I start my app:

`09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethodN
ative(Native Method)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.dispatchCallJ
SMethodNative(Runtime.java:1197)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethodI
mpl(Runtime.java:1061)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethod(
Runtime.java:1047)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethod(
Runtime.java:1028)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethod(
Runtime.java:1018)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethodN
ative(Native Method)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.dispatchCallJ
SMethodNative(Runtime.java:1197)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethodI
mpl(Runtime.java:1061)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethod(
Runtime.java:1047)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethod(
Runtime.java:1028)
09-20 09:44:19.734  3278  3278 E Fabric  :      at com.tns.Runtime.callJSMethod(
Runtime.java:1018)`

**Comment by hypery2k** [comment]
sorry to say, but I'm unable to reproduce this error
