### ISSUE TITLE
fabric website launching on every new build on iOS

### ISSUE THREAD

**Issue by sittingbool** [hypery2k/nativescript-fabric#97]
Every time tns makes a build without auto reload, meaning a fresh build, fabric starts uninvited and opens the website many time. for me it does that up to about 50 times (50 tabs in 20 sek), which could be because of #85 ... I has to shut down my browser because it couldn't even close all those tabs anymore.

**Comment by hypery2k** [comment]
could you try with `nativescript-fabric@1.0.6-ci-build-19`?

**Comment by hypery2k** [comment]
closed due to no response
